# Generated by Django 6.0.2 on 2026-02-16 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_holding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AddField(
            model_name='holding',
            name='first_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='last_purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['user', 'stock'], name='trading_hol_user_id_f9df75_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['user', '-updated_at'], name='trading_hol_user_id_eb3000_idx'),
        ),
    ]
