# Generated by Django 6.0.2 on 2026-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price_source',
            field=models.CharField(choices=[('nepse_api_live', 'Live NEPSE API'), ('nepse_api_cached', 'Cached NEPSE API'), ('database_cache', 'Database Cache'), ('database_fallback', 'Emergency Fallback'), ('mock_data', 'Mock Data (Development)')], default='mock_data', help_text='Where the price came from', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='EXECUTED', max_length=10),
        ),
    ]
